apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phase5-todo

resources:
  - namespace.yaml
  - base/postgres.yaml
  - base/redis.yaml
  - base/backend.yaml
  - base/frontend.yaml
  - base/ingress.yaml
