apiVersion: v2
name: phase5-todo
description: Phase-5 Todo Application Helm Chart
type: application
version: 1.0.0
appVersion: "5.0.0"
keywords:
  - todo
  - fastapi
  - nextjs
  - kubernetes
maintainers:
  - name: Phase-5 Team
